# Generated by Django 3.1.14 on 2022-02-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20220201_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='photo',
        ),
    ]
