# Generated by Django 3.1.14 on 2022-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_remove_pokemon_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
