# Generated by Django 2.2.5 on 2022-02-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0021_auto_20220205_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pokemon_type',
            new_name='pokemon',
        ),
    ]
